package com.mycollegemart.backend.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mycollegemart.backend.model.User;
import com.mycollegemart.backend.model.UserSettings;
import com.mycollegemart.backend.repository.UserRepository;
import com.mycollegemart.backend.repository.UserSettingsRepository;
import com.mycollegemart.backend.util.JwtUtil;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.web.servlet.MockMvc;

import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc
@TestPropertySource(properties = {
        "spring.datasource.url=jdbc:h2:mem:settings_test_db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.sql.init.mode=never",
        "spring.jpa.show-sql=false",
        "jwt.secret=test-secret-key-which-is-long-enough-1234567890",
        "jwt.expiration=3600000"
})
class SettingsControllerIntegrationTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private UserSettingsRepository userSettingsRepository;

    @Autowired
    private JwtUtil jwtUtil;

    @BeforeEach
    void setupSchema() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS user_settings");
        jdbcTemplate.execute("DROP TABLE IF EXISTS user_wishlist");
        jdbcTemplate.execute("DROP TABLE IF EXISTS users");

        jdbcTemplate.execute("""
                CREATE TABLE users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    email VARCHAR(255) NOT NULL UNIQUE,
                    password VARCHAR(255),
                    display_name VARCHAR(255),
                    is_prime_member BOOLEAN NOT NULL DEFAULT FALSE,
                    prime_expiry_date VARCHAR(255),
                    account_type VARCHAR(32) NOT NULL DEFAULT 'INDIVIDUAL',
                    merchant_verification_status VARCHAR(32) NOT NULL DEFAULT 'NOT_REQUIRED',
                    shop_name VARCHAR(255),
                    shop_tagline VARCHAR(255),
                    shop_description CLOB,
                    shop_phone VARCHAR(32),
                    shop_campus_location VARCHAR(255),
                    google_id VARCHAR(255)
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE user_wishlist (
                    user_id BIGINT NOT NULL,
                    product_id BIGINT NOT NULL,
                    PRIMARY KEY (user_id, product_id)
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE user_settings (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL UNIQUE,
                    phone_number VARCHAR(32),
                    campus_location VARCHAR(255),
                    bio CLOB,
                    email_notifications BOOLEAN NOT NULL DEFAULT TRUE,
                    order_updates BOOLEAN NOT NULL DEFAULT TRUE,
                    marketing_emails BOOLEAN NOT NULL DEFAULT FALSE,
                    two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,
                    preferred_language VARCHAR(16) NOT NULL DEFAULT 'EN',
                    theme_mode VARCHAR(16) NOT NULL DEFAULT 'SYSTEM'
                )
                """);

        userSettingsRepository.deleteAll();
        userRepository.deleteAll();
    }

    @Test
    void getSettingsRequiresBearerToken() throws Exception {
        mockMvc.perform(get("/api/settings/me"))
                .andExpect(status().isUnauthorized())
                .andExpect(jsonPath("$.message").value("Please sign in"));
    }

    @Test
    void getSettingsReturnsOnlyAuthenticatedUsersSettings() throws Exception {
        User alice = createUser("alice.settings@test.com", "Alice");
        User bob = createUser("bob.settings@test.com", "Bob");

        createUserSettings(alice.getId(), "DARK", "HI", "Alice campus");
        createUserSettings(bob.getId(), "LIGHT", "EN", "Bob campus");

        mockMvc.perform(get("/api/settings/me")
                .header("Authorization", bearerTokenFor(alice)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.profile.id").value(alice.getId().intValue()))
                .andExpect(jsonPath("$.profile.displayName").value("Alice"))
                .andExpect(jsonPath("$.preferences.themeMode").value("DARK"))
                .andExpect(jsonPath("$.preferences.preferredLanguage").value("HI"))
                .andExpect(jsonPath("$.preferences.campusLocation").value("Alice campus"));

        mockMvc.perform(get("/api/settings/me")
                .header("Authorization", bearerTokenFor(bob)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.profile.id").value(bob.getId().intValue()))
                .andExpect(jsonPath("$.profile.displayName").value("Bob"))
                .andExpect(jsonPath("$.preferences.themeMode").value("LIGHT"))
                .andExpect(jsonPath("$.preferences.preferredLanguage").value("EN"))
                .andExpect(jsonPath("$.preferences.campusLocation").value("Bob campus"));
    }

    @Test
    void updateSettingsOnlyUpdatesAuthenticatedUser() throws Exception {
        User alice = createUser("alice.update@test.com", "Alice");
        User bob = createUser("bob.update@test.com", "Bob");

        UserSettings aliceSettings = createUserSettings(alice.getId(), "SYSTEM", "EN", "A block");
        UserSettings bobSettings = createUserSettings(bob.getId(), "DARK", "MR", "B block");

        Map<String, Object> payload = Map.of(
                "displayName", "Alice Updated",
                "phoneNumber", "9876543210",
                "campusLocation", "Library block",
                "bio", "Helping students with project guidance",
                "emailNotifications", true,
                "orderUpdates", false,
                "marketingEmails", true,
                "twoFactorEnabled", true,
                "preferredLanguage", "HI",
                "themeMode", "LIGHT");

        mockMvc.perform(put("/api/settings/me")
                .header("Authorization", bearerTokenFor(alice))
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(payload)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.profile.id").value(alice.getId().intValue()))
                .andExpect(jsonPath("$.profile.displayName").value("Alice Updated"))
                .andExpect(jsonPath("$.preferences.themeMode").value("LIGHT"))
                .andExpect(jsonPath("$.preferences.preferredLanguage").value("HI"))
                .andExpect(jsonPath("$.preferences.orderUpdates").value(false))
                .andExpect(jsonPath("$.preferences.twoFactorEnabled").value(true));

        User refreshedAlice = userRepository.findById(alice.getId()).orElseThrow();
        User refreshedBob = userRepository.findById(bob.getId()).orElseThrow();
        UserSettings refreshedAliceSettings = userSettingsRepository.findById(aliceSettings.getId()).orElseThrow();
        UserSettings refreshedBobSettings = userSettingsRepository.findById(bobSettings.getId()).orElseThrow();

        assertThat(refreshedAlice.getDisplayName()).isEqualTo("Alice Updated");
        assertThat(refreshedAliceSettings.getThemeMode()).isEqualTo("LIGHT");
        assertThat(refreshedAliceSettings.getPreferredLanguage()).isEqualTo("HI");
        assertThat(refreshedAliceSettings.isOrderUpdates()).isFalse();

        assertThat(refreshedBob.getDisplayName()).isEqualTo("Bob");
        assertThat(refreshedBobSettings.getThemeMode()).isEqualTo("DARK");
        assertThat(refreshedBobSettings.getPreferredLanguage()).isEqualTo("MR");
        assertThat(refreshedBobSettings.getCampusLocation()).isEqualTo("B block");
    }

    @Test
    void updateSettingsRejectsUnsupportedPreferredLanguage() throws Exception {
        User user = createUser("invalid.language@test.com", "Lang User");

        Map<String, Object> payload = Map.of(
                "preferredLanguage", "FR");

        mockMvc.perform(put("/api/settings/me")
                .header("Authorization", bearerTokenFor(user))
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(payload)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message").value("preferredLanguage is not supported"));

        UserSettings persisted = userSettingsRepository.findByUserId(user.getId()).orElseThrow();
        assertThat(persisted.getPreferredLanguage()).isEqualTo("EN");
    }

    @Test
    void updateSettingsRejectsUnsupportedThemeMode() throws Exception {
        User user = createUser("invalid.theme@test.com", "Theme User");

        Map<String, Object> payload = Map.of(
                "themeMode", "AMOLED");

        mockMvc.perform(put("/api/settings/me")
                .header("Authorization", bearerTokenFor(user))
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(payload)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message").value("themeMode is not supported"));

        UserSettings persisted = userSettingsRepository.findByUserId(user.getId()).orElseThrow();
        assertThat(persisted.getThemeMode()).isEqualTo("SYSTEM");
    }

    private User createUser(String email, String displayName) {
        User user = new User();
        user.setEmail(email);
        user.setPassword("encoded-password");
        user.setDisplayName(displayName);
        user.setAccountType("INDIVIDUAL");
        user.setMerchantVerificationStatus("NOT_REQUIRED");
        user.setPrimeMember(false);
        return userRepository.save(user);
    }

    private UserSettings createUserSettings(Long userId, String themeMode, String preferredLanguage,
            String campusLocation) {
        UserSettings settings = new UserSettings();
        settings.setUserId(userId);
        settings.setThemeMode(themeMode);
        settings.setPreferredLanguage(preferredLanguage);
        settings.setCampusLocation(campusLocation);
        settings.setEmailNotifications(true);
        settings.setOrderUpdates(true);
        settings.setMarketingEmails(false);
        settings.setTwoFactorEnabled(false);
        return userSettingsRepository.save(settings);
    }

    private String bearerTokenFor(User user) {
        return "Bearer " + jwtUtil.generateToken(user.getId(), user.getEmail());
    }
}
