-- MyCollegeMart PostgreSQL schema
-- This script is executed by Spring Boot on backend startup.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255),
    display_name VARCHAR(255),
    is_prime_member BOOLEAN NOT NULL DEFAULT FALSE,
    prime_expiry_date VARCHAR(255),
    google_id VARCHAR(255)
);

-- Patch existing installations where users table was created before these columns existed.
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS password VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS display_name VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS google_id VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS prime_expiry_date VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS is_prime_member BOOLEAN;
UPDATE users SET is_prime_member = FALSE WHERE is_prime_member IS NULL;
ALTER TABLE IF EXISTS users ALTER COLUMN is_prime_member SET DEFAULT FALSE;
ALTER TABLE IF EXISTS users ALTER COLUMN is_prime_member SET NOT NULL;

CREATE TABLE IF NOT EXISTS product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255),
    price DOUBLE PRECISION,
    image_url VARCHAR(255)
);

ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS description VARCHAR(255);
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS price DOUBLE PRECISION;
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS image_url VARCHAR(255);

CREATE TABLE IF NOT EXISTS cart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT
);

ALTER TABLE IF EXISTS cart ADD COLUMN IF NOT EXISTS user_id BIGINT;

CREATE TABLE IF NOT EXISTS cart_products (
    cart_id BIGINT NOT NULL,
    products_id BIGINT NOT NULL,
    CONSTRAINT uk_cart_products_products UNIQUE (products_id),
    CONSTRAINT fk_cart_products_cart FOREIGN KEY (cart_id) REFERENCES cart (id),
    CONSTRAINT fk_cart_products_product FOREIGN KEY (products_id) REFERENCES product (id)
);

CREATE INDEX IF NOT EXISTS idx_cart_user_id ON cart (user_id);
