-- MyCollegeMart PostgreSQL schema
-- Single source of truth for schema initialization.
-- Backend loads this file via spring.sql.init.schema-locations.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255),
    display_name VARCHAR(255),
    account_type VARCHAR(32) NOT NULL DEFAULT 'INDIVIDUAL',
    merchant_verification_status VARCHAR(32) NOT NULL DEFAULT 'NOT_REQUIRED',
    shop_name VARCHAR(255),
    shop_tagline VARCHAR(255),
    shop_description TEXT,
    shop_phone VARCHAR(32),
    shop_campus_location VARCHAR(255),
    is_prime_member BOOLEAN NOT NULL DEFAULT FALSE,
    prime_expiry_date VARCHAR(255),
    google_id VARCHAR(255),
    profile_image BYTEA,
    profile_image_content_type VARCHAR(100)
);

-- Patch existing installations where users table was created before these columns existed.
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS password VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS display_name VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS account_type VARCHAR(32);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS merchant_verification_status VARCHAR(32);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS shop_name VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS shop_tagline VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS shop_description TEXT;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS shop_phone VARCHAR(32);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS shop_campus_location VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS google_id VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS profile_image BYTEA;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS profile_image_content_type VARCHAR(100);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS prime_expiry_date VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS is_prime_member BOOLEAN;
UPDATE users SET account_type = 'INDIVIDUAL' WHERE account_type IS NULL;
ALTER TABLE IF EXISTS users ALTER COLUMN account_type SET DEFAULT 'INDIVIDUAL';
ALTER TABLE IF EXISTS users ALTER COLUMN account_type SET NOT NULL;
UPDATE users
SET merchant_verification_status = CASE
    WHEN account_type = 'MERCHANT' THEN 'PENDING'
    ELSE 'NOT_REQUIRED'
END
WHERE merchant_verification_status IS NULL;
ALTER TABLE IF EXISTS users ALTER COLUMN merchant_verification_status SET DEFAULT 'NOT_REQUIRED';
ALTER TABLE IF EXISTS users ALTER COLUMN merchant_verification_status SET NOT NULL;
UPDATE users SET is_prime_member = FALSE WHERE is_prime_member IS NULL;
ALTER TABLE IF EXISTS users ALTER COLUMN is_prime_member SET DEFAULT FALSE;
ALTER TABLE IF EXISTS users ALTER COLUMN is_prime_member SET NOT NULL;

CREATE TABLE IF NOT EXISTS wallet_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    transaction_type VARCHAR(32) NOT NULL DEFAULT 'CREDIT',
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    currency VARCHAR(8) NOT NULL DEFAULT 'INR',
    description VARCHAR(255),
    razorpay_order_id VARCHAR(255),
    razorpay_payment_id VARCHAR(255),
    razorpay_signature VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_wallet_transaction_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

ALTER TABLE IF EXISTS wallet_transaction ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE IF EXISTS wallet_transaction ADD COLUMN IF NOT EXISTS transaction_type VARCHAR(32);
ALTER TABLE IF EXISTS wallet_transaction ADD COLUMN IF NOT EXISTS status VARCHAR(32);
ALTER TABLE IF EXISTS wallet_transaction ADD COLUMN IF NOT EXISTS amount DOUBLE PRECISION;
ALTER TABLE IF EXISTS wallet_transaction ADD COLUMN IF NOT EXISTS currency VARCHAR(8);
ALTER TABLE IF EXISTS wallet_transaction ADD COLUMN IF NOT EXISTS description VARCHAR(255);
ALTER TABLE IF EXISTS wallet_transaction ADD COLUMN IF NOT EXISTS razorpay_order_id VARCHAR(255);
ALTER TABLE IF EXISTS wallet_transaction ADD COLUMN IF NOT EXISTS razorpay_payment_id VARCHAR(255);
ALTER TABLE IF EXISTS wallet_transaction ADD COLUMN IF NOT EXISTS razorpay_signature VARCHAR(255);
ALTER TABLE IF EXISTS wallet_transaction ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS wallet_transaction ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

UPDATE wallet_transaction SET transaction_type = 'CREDIT' WHERE transaction_type IS NULL;
UPDATE wallet_transaction SET status = 'PENDING' WHERE status IS NULL;
UPDATE wallet_transaction SET amount = 0 WHERE amount IS NULL;
UPDATE wallet_transaction SET currency = 'INR' WHERE currency IS NULL;
UPDATE wallet_transaction SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE wallet_transaction SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL;

ALTER TABLE IF EXISTS wallet_transaction ALTER COLUMN transaction_type SET DEFAULT 'CREDIT';
ALTER TABLE IF EXISTS wallet_transaction ALTER COLUMN status SET DEFAULT 'PENDING';
ALTER TABLE IF EXISTS wallet_transaction ALTER COLUMN amount SET DEFAULT 0;
ALTER TABLE IF EXISTS wallet_transaction ALTER COLUMN currency SET DEFAULT 'INR';
ALTER TABLE IF EXISTS wallet_transaction ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS wallet_transaction ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE IF EXISTS wallet_transaction ALTER COLUMN transaction_type SET NOT NULL;
ALTER TABLE IF EXISTS wallet_transaction ALTER COLUMN status SET NOT NULL;
ALTER TABLE IF EXISTS wallet_transaction ALTER COLUMN amount SET NOT NULL;
ALTER TABLE IF EXISTS wallet_transaction ALTER COLUMN currency SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_wallet_transaction_user_id_created_at
    ON wallet_transaction (user_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_wallet_transaction_razorpay_order_id
    ON wallet_transaction (razorpay_order_id) WHERE razorpay_order_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_wallet_transaction_razorpay_payment_id
    ON wallet_transaction (razorpay_payment_id) WHERE razorpay_payment_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS user_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    phone_number VARCHAR(32),
    campus_location VARCHAR(255),
    bio TEXT,
    email_notifications BOOLEAN NOT NULL DEFAULT TRUE,
    order_updates BOOLEAN NOT NULL DEFAULT TRUE,
    marketing_emails BOOLEAN NOT NULL DEFAULT FALSE,
    two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    preferred_language VARCHAR(16) NOT NULL DEFAULT 'EN',
    theme_mode VARCHAR(16) NOT NULL DEFAULT 'SYSTEM',
    CONSTRAINT fk_user_settings_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

ALTER TABLE IF EXISTS user_settings ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE IF EXISTS user_settings ADD COLUMN IF NOT EXISTS phone_number VARCHAR(32);
ALTER TABLE IF EXISTS user_settings ADD COLUMN IF NOT EXISTS campus_location VARCHAR(255);
ALTER TABLE IF EXISTS user_settings ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE IF EXISTS user_settings ADD COLUMN IF NOT EXISTS email_notifications BOOLEAN;
ALTER TABLE IF EXISTS user_settings ADD COLUMN IF NOT EXISTS order_updates BOOLEAN;
ALTER TABLE IF EXISTS user_settings ADD COLUMN IF NOT EXISTS marketing_emails BOOLEAN;
ALTER TABLE IF EXISTS user_settings ADD COLUMN IF NOT EXISTS two_factor_enabled BOOLEAN;
ALTER TABLE IF EXISTS user_settings ADD COLUMN IF NOT EXISTS preferred_language VARCHAR(16);
ALTER TABLE IF EXISTS user_settings ADD COLUMN IF NOT EXISTS theme_mode VARCHAR(16);

UPDATE user_settings SET email_notifications = TRUE WHERE email_notifications IS NULL;
UPDATE user_settings SET order_updates = TRUE WHERE order_updates IS NULL;
UPDATE user_settings SET marketing_emails = FALSE WHERE marketing_emails IS NULL;
UPDATE user_settings SET two_factor_enabled = FALSE WHERE two_factor_enabled IS NULL;
UPDATE user_settings SET preferred_language = 'EN' WHERE preferred_language IS NULL;
UPDATE user_settings SET theme_mode = 'SYSTEM' WHERE theme_mode IS NULL;

ALTER TABLE IF EXISTS user_settings ALTER COLUMN email_notifications SET DEFAULT TRUE;
ALTER TABLE IF EXISTS user_settings ALTER COLUMN order_updates SET DEFAULT TRUE;
ALTER TABLE IF EXISTS user_settings ALTER COLUMN marketing_emails SET DEFAULT FALSE;
ALTER TABLE IF EXISTS user_settings ALTER COLUMN two_factor_enabled SET DEFAULT FALSE;
ALTER TABLE IF EXISTS user_settings ALTER COLUMN preferred_language SET DEFAULT 'EN';
ALTER TABLE IF EXISTS user_settings ALTER COLUMN theme_mode SET DEFAULT 'SYSTEM';

ALTER TABLE IF EXISTS user_settings ALTER COLUMN email_notifications SET NOT NULL;
ALTER TABLE IF EXISTS user_settings ALTER COLUMN order_updates SET NOT NULL;
ALTER TABLE IF EXISTS user_settings ALTER COLUMN marketing_emails SET NOT NULL;
ALTER TABLE IF EXISTS user_settings ALTER COLUMN two_factor_enabled SET NOT NULL;
ALTER TABLE IF EXISTS user_settings ALTER COLUMN preferred_language SET NOT NULL;
ALTER TABLE IF EXISTS user_settings ALTER COLUMN theme_mode SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_settings_user_id_unique ON user_settings (user_id);

CREATE TABLE IF NOT EXISTS product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description TEXT,
    price DOUBLE PRECISION,
    listed_by_user_id BIGINT,
    image_url VARCHAR(255),
    category VARCHAR(255),
    branch VARCHAR(255),
    semester VARCHAR(32),
    is_prime_exclusive BOOLEAN NOT NULL DEFAULT FALSE,
    rating DOUBLE PRECISION,
    highlights_json TEXT,
    specs_json TEXT,
    external_video_url VARCHAR(1024),
    in_stock BOOLEAN NOT NULL DEFAULT TRUE,
    stock_quantity INTEGER,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS description VARCHAR(255);
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS price DOUBLE PRECISION;
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS listed_by_user_id BIGINT;
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS image_url VARCHAR(255);
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS category VARCHAR(255);
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS branch VARCHAR(255);
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS semester VARCHAR(32);
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS is_prime_exclusive BOOLEAN;
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS rating DOUBLE PRECISION;
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS highlights_json TEXT;
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS specs_json TEXT;
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS external_video_url VARCHAR(1024);
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS in_stock BOOLEAN;
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS stock_quantity INTEGER;
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS product ALTER COLUMN description TYPE TEXT;
UPDATE product SET is_prime_exclusive = FALSE WHERE is_prime_exclusive IS NULL;
ALTER TABLE IF EXISTS product ALTER COLUMN is_prime_exclusive SET DEFAULT FALSE;
ALTER TABLE IF EXISTS product ALTER COLUMN is_prime_exclusive SET NOT NULL;
UPDATE product SET in_stock = TRUE WHERE in_stock IS NULL;
ALTER TABLE IF EXISTS product ALTER COLUMN in_stock SET DEFAULT TRUE;
ALTER TABLE IF EXISTS product ALTER COLUMN in_stock SET NOT NULL;
UPDATE product SET stock_quantity = 0 WHERE in_stock = FALSE AND stock_quantity IS NULL;
UPDATE product SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
ALTER TABLE IF EXISTS product ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX IF NOT EXISTS idx_product_listed_by_user_id ON product (listed_by_user_id);

CREATE TABLE IF NOT EXISTS product_question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    asked_by_user_id BIGINT,
    author_name VARCHAR(255) NOT NULL,
    question_text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_question_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE,
    CONSTRAINT fk_product_question_user FOREIGN KEY (asked_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

ALTER TABLE IF EXISTS product_question ADD COLUMN IF NOT EXISTS product_id BIGINT;
ALTER TABLE IF EXISTS product_question ADD COLUMN IF NOT EXISTS asked_by_user_id BIGINT;
ALTER TABLE IF EXISTS product_question ADD COLUMN IF NOT EXISTS author_name VARCHAR(255);
ALTER TABLE IF EXISTS product_question ADD COLUMN IF NOT EXISTS question_text TEXT;
ALTER TABLE IF EXISTS product_question ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;

UPDATE product_question SET author_name = 'Campus User' WHERE author_name IS NULL OR author_name = '';
UPDATE product_question SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;

ALTER TABLE IF EXISTS product_question ALTER COLUMN author_name SET NOT NULL;
ALTER TABLE IF EXISTS product_question ALTER COLUMN question_text SET NOT NULL;
ALTER TABLE IF EXISTS product_question ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_product_question_product_id ON product_question (product_id, created_at DESC);

CREATE TABLE IF NOT EXISTS product_question_answer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    answered_by_user_id BIGINT,
    author_name VARCHAR(255) NOT NULL,
    answer_text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_question_answer_question FOREIGN KEY (question_id) REFERENCES product_question (id) ON DELETE CASCADE,
    CONSTRAINT fk_product_question_answer_user FOREIGN KEY (answered_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

ALTER TABLE IF EXISTS product_question_answer ADD COLUMN IF NOT EXISTS question_id BIGINT;
ALTER TABLE IF EXISTS product_question_answer ADD COLUMN IF NOT EXISTS answered_by_user_id BIGINT;
ALTER TABLE IF EXISTS product_question_answer ADD COLUMN IF NOT EXISTS author_name VARCHAR(255);
ALTER TABLE IF EXISTS product_question_answer ADD COLUMN IF NOT EXISTS answer_text TEXT;
ALTER TABLE IF EXISTS product_question_answer ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;

UPDATE product_question_answer SET author_name = 'Campus User' WHERE author_name IS NULL OR author_name = '';
UPDATE product_question_answer SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;

ALTER TABLE IF EXISTS product_question_answer ALTER COLUMN author_name SET NOT NULL;
ALTER TABLE IF EXISTS product_question_answer ALTER COLUMN answer_text SET NOT NULL;
ALTER TABLE IF EXISTS product_question_answer ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_product_question_answer_question_id
    ON product_question_answer (question_id, created_at);

CREATE TABLE IF NOT EXISTS user_wishlist (
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, product_id),
    CONSTRAINT fk_user_wishlist_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_wishlist_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT
);

ALTER TABLE IF EXISTS cart ADD COLUMN IF NOT EXISTS user_id BIGINT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_cart_user_id_unique ON cart (user_id);

CREATE TABLE IF NOT EXISTS cart_products (
    cart_id BIGINT NOT NULL,
    products_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT fk_cart_products_cart FOREIGN KEY (cart_id) REFERENCES cart (id),
    CONSTRAINT fk_cart_products_product FOREIGN KEY (products_id) REFERENCES product (id)
);

ALTER TABLE IF EXISTS cart_products ADD COLUMN IF NOT EXISTS quantity INTEGER;
UPDATE cart_products SET quantity = 1 WHERE quantity IS NULL;
ALTER TABLE IF EXISTS cart_products ALTER COLUMN quantity SET DEFAULT 1;
ALTER TABLE IF EXISTS cart_products ALTER COLUMN quantity SET NOT NULL;
ALTER TABLE IF EXISTS cart_products DROP CONSTRAINT IF EXISTS uk_cart_products_products;
CREATE UNIQUE INDEX IF NOT EXISTS idx_cart_products_cart_product_unique ON cart_products (cart_id, products_id);

CREATE INDEX IF NOT EXISTS idx_cart_user_id ON cart (user_id);

CREATE TABLE IF NOT EXISTS purchase_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    payment_method VARCHAR(64) NOT NULL,
    payment_status VARCHAR(64) NOT NULL,
    order_status VARCHAR(64) NOT NULL,
    delivery_option VARCHAR(255),
    subtotal DOUBLE PRECISION NOT NULL DEFAULT 0,
    wallet_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    amount_due DOUBLE PRECISION NOT NULL DEFAULT 0,
    amount_paid DOUBLE PRECISION NOT NULL DEFAULT 0,
    currency VARCHAR(8) NOT NULL DEFAULT 'INR',
    razorpay_order_id VARCHAR(255),
    razorpay_payment_id VARCHAR(255),
    razorpay_signature VARCHAR(255),
    tracking_number VARCHAR(128),
    carrier_name VARCHAR(128),
    carrier_contact VARCHAR(64),
    current_location VARCHAR(255),
    estimated_delivery_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    last_tracking_update_at TIMESTAMPTZ,
    items_json TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS order_number VARCHAR(255);
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS payment_method VARCHAR(64);
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS payment_status VARCHAR(64);
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS order_status VARCHAR(64);
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS delivery_option VARCHAR(255);
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS subtotal DOUBLE PRECISION;
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS wallet_amount DOUBLE PRECISION;
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS amount_due DOUBLE PRECISION;
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS amount_paid DOUBLE PRECISION;
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS currency VARCHAR(8);
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS razorpay_order_id VARCHAR(255);
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS razorpay_payment_id VARCHAR(255);
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS razorpay_signature VARCHAR(255);
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS tracking_number VARCHAR(128);
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS carrier_name VARCHAR(128);
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS carrier_contact VARCHAR(64);
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS current_location VARCHAR(255);
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS estimated_delivery_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS last_tracking_update_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS items_json TEXT;
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

UPDATE purchase_order SET subtotal = 0 WHERE subtotal IS NULL;
UPDATE purchase_order SET wallet_amount = 0 WHERE wallet_amount IS NULL;
UPDATE purchase_order SET amount_due = 0 WHERE amount_due IS NULL;
UPDATE purchase_order SET amount_paid = 0 WHERE amount_paid IS NULL;
UPDATE purchase_order SET currency = 'INR' WHERE currency IS NULL;
UPDATE purchase_order SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE purchase_order SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL;
UPDATE purchase_order SET tracking_number = CONCAT('MCMTRK-', LPAD(id::TEXT, 8, '0')) WHERE tracking_number IS NULL;
UPDATE purchase_order SET carrier_name = 'MCM Logistics' WHERE carrier_name IS NULL OR carrier_name = '';
UPDATE purchase_order SET carrier_contact = '+91-1800-123-456' WHERE carrier_contact IS NULL OR carrier_contact = '';
UPDATE purchase_order SET current_location = 'Order Processing Center' WHERE current_location IS NULL OR current_location = '';
UPDATE purchase_order SET estimated_delivery_at = created_at + INTERVAL '5 days' WHERE estimated_delivery_at IS NULL;
UPDATE purchase_order SET last_tracking_update_at = updated_at WHERE last_tracking_update_at IS NULL;
UPDATE purchase_order SET delivered_at = updated_at
WHERE delivered_at IS NULL
    AND UPPER(COALESCE(order_status, '')) = 'DELIVERED';

ALTER TABLE IF EXISTS purchase_order ALTER COLUMN subtotal SET DEFAULT 0;
ALTER TABLE IF EXISTS purchase_order ALTER COLUMN wallet_amount SET DEFAULT 0;
ALTER TABLE IF EXISTS purchase_order ALTER COLUMN amount_due SET DEFAULT 0;
ALTER TABLE IF EXISTS purchase_order ALTER COLUMN amount_paid SET DEFAULT 0;
ALTER TABLE IF EXISTS purchase_order ALTER COLUMN currency SET DEFAULT 'INR';
ALTER TABLE IF EXISTS purchase_order ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS purchase_order ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX IF NOT EXISTS idx_purchase_order_order_number ON purchase_order (order_number);
CREATE UNIQUE INDEX IF NOT EXISTS idx_purchase_order_razorpay_order_id ON purchase_order (razorpay_order_id) WHERE razorpay_order_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_purchase_order_user_id ON purchase_order (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_purchase_order_tracking_number ON purchase_order (tracking_number);

CREATE TABLE IF NOT EXISTS purchase_order_tracking_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL,
    event_status VARCHAR(64) NOT NULL,
    event_title VARCHAR(255) NOT NULL,
    event_description TEXT,
    event_location VARCHAR(255),
    event_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_purchase_order_tracking_event_order
        FOREIGN KEY (purchase_order_id) REFERENCES purchase_order (id) ON DELETE CASCADE
);

ALTER TABLE IF EXISTS purchase_order_tracking_event ADD COLUMN IF NOT EXISTS purchase_order_id BIGINT;
ALTER TABLE IF EXISTS purchase_order_tracking_event ADD COLUMN IF NOT EXISTS event_status VARCHAR(64);
ALTER TABLE IF EXISTS purchase_order_tracking_event ADD COLUMN IF NOT EXISTS event_title VARCHAR(255);
ALTER TABLE IF EXISTS purchase_order_tracking_event ADD COLUMN IF NOT EXISTS event_description TEXT;
ALTER TABLE IF EXISTS purchase_order_tracking_event ADD COLUMN IF NOT EXISTS event_location VARCHAR(255);
ALTER TABLE IF EXISTS purchase_order_tracking_event ADD COLUMN IF NOT EXISTS event_time TIMESTAMPTZ;
ALTER TABLE IF EXISTS purchase_order_tracking_event ADD COLUMN IF NOT EXISTS sort_order INTEGER;
ALTER TABLE IF EXISTS purchase_order_tracking_event ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;

UPDATE purchase_order_tracking_event
SET event_time = CURRENT_TIMESTAMP
WHERE event_time IS NULL;

UPDATE purchase_order_tracking_event
SET sort_order = 0
WHERE sort_order IS NULL;

ALTER TABLE IF EXISTS purchase_order_tracking_event ALTER COLUMN event_time SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS purchase_order_tracking_event ALTER COLUMN event_time SET NOT NULL;
ALTER TABLE IF EXISTS purchase_order_tracking_event ALTER COLUMN sort_order SET DEFAULT 0;
ALTER TABLE IF EXISTS purchase_order_tracking_event ALTER COLUMN sort_order SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_purchase_order_tracking_event_order
    ON purchase_order_tracking_event (purchase_order_id, sort_order, event_time);

CREATE TABLE IF NOT EXISTS media_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_type VARCHAR(64) NOT NULL,
    owner_id BIGINT NOT NULL,
    media_type VARCHAR(32) NOT NULL,
    file_name VARCHAR(255),
    content_type VARCHAR(255),
    file_size BIGINT,
    display_order INTEGER NOT NULL DEFAULT 0,
    data BYTEA NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE IF EXISTS media_asset ADD COLUMN IF NOT EXISTS owner_type VARCHAR(64);
ALTER TABLE IF EXISTS media_asset ADD COLUMN IF NOT EXISTS owner_id BIGINT;
ALTER TABLE IF EXISTS media_asset ADD COLUMN IF NOT EXISTS media_type VARCHAR(32);
ALTER TABLE IF EXISTS media_asset ADD COLUMN IF NOT EXISTS file_name VARCHAR(255);
ALTER TABLE IF EXISTS media_asset ADD COLUMN IF NOT EXISTS content_type VARCHAR(255);
ALTER TABLE IF EXISTS media_asset ADD COLUMN IF NOT EXISTS file_size BIGINT;
ALTER TABLE IF EXISTS media_asset ADD COLUMN IF NOT EXISTS display_order INTEGER;
ALTER TABLE IF EXISTS media_asset ADD COLUMN IF NOT EXISTS data BYTEA;
ALTER TABLE IF EXISTS media_asset ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;

UPDATE media_asset SET display_order = 0 WHERE display_order IS NULL;
ALTER TABLE IF EXISTS media_asset ALTER COLUMN display_order SET DEFAULT 0;
ALTER TABLE IF EXISTS media_asset ALTER COLUMN display_order SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_media_asset_owner ON media_asset (owner_type, owner_id, display_order);

CREATE TABLE IF NOT EXISTS skill_service (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    type VARCHAR(64) NOT NULL,
    description TEXT,
    price DOUBLE PRECISION NOT NULL DEFAULT 0,
    branch VARCHAR(255) NOT NULL,
    semester VARCHAR(16) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE IF EXISTS skill_service ADD COLUMN IF NOT EXISTS title VARCHAR(255);
ALTER TABLE IF EXISTS skill_service ADD COLUMN IF NOT EXISTS type VARCHAR(64);
ALTER TABLE IF EXISTS skill_service ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE IF EXISTS skill_service ADD COLUMN IF NOT EXISTS price DOUBLE PRECISION;
ALTER TABLE IF EXISTS skill_service ADD COLUMN IF NOT EXISTS branch VARCHAR(255);
ALTER TABLE IF EXISTS skill_service ADD COLUMN IF NOT EXISTS semester VARCHAR(16);
ALTER TABLE IF EXISTS skill_service ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
UPDATE skill_service SET price = 0 WHERE price IS NULL;
UPDATE skill_service SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
ALTER TABLE IF EXISTS skill_service ALTER COLUMN price SET DEFAULT 0;
ALTER TABLE IF EXISTS skill_service ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS assignment_help_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_service_id BIGINT,
    user_id BIGINT,
    service_type VARCHAR(64) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    description TEXT,
    branch VARCHAR(255) NOT NULL,
    semester VARCHAR(16) NOT NULL,
    deadline VARCHAR(32) NOT NULL,
    total_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    amount_paid DOUBLE PRECISION NOT NULL DEFAULT 0,
    payment_method VARCHAR(32) NOT NULL DEFAULT 'ONLINE',
    payment_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    currency VARCHAR(8) NOT NULL DEFAULT 'INR',
    razorpay_order_id VARCHAR(255),
    razorpay_payment_id VARCHAR(255),
    razorpay_signature VARCHAR(255),
    status VARCHAR(32) NOT NULL DEFAULT 'SUBMITTED',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_assignment_help_skill_service FOREIGN KEY (skill_service_id) REFERENCES skill_service (id) ON DELETE SET NULL
);

ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS skill_service_id BIGINT;
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS service_type VARCHAR(64);
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS subject VARCHAR(255);
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS topic VARCHAR(255);
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS branch VARCHAR(255);
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS semester VARCHAR(16);
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS deadline VARCHAR(32);
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS total_amount DOUBLE PRECISION;
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS amount_paid DOUBLE PRECISION;
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS payment_method VARCHAR(32);
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS payment_status VARCHAR(32);
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS currency VARCHAR(8);
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS razorpay_order_id VARCHAR(255);
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS razorpay_payment_id VARCHAR(255);
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS razorpay_signature VARCHAR(255);
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS status VARCHAR(32);
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
UPDATE assignment_help_request SET total_amount = 0 WHERE total_amount IS NULL;
UPDATE assignment_help_request SET amount_paid = 0 WHERE amount_paid IS NULL;
UPDATE assignment_help_request SET payment_method = 'ONLINE' WHERE payment_method IS NULL;
UPDATE assignment_help_request SET payment_status = 'PENDING' WHERE payment_status IS NULL;
UPDATE assignment_help_request SET currency = 'INR' WHERE currency IS NULL;
UPDATE assignment_help_request SET status = 'SUBMITTED' WHERE status IS NULL;
UPDATE assignment_help_request SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
ALTER TABLE IF EXISTS assignment_help_request ALTER COLUMN total_amount SET DEFAULT 0;
ALTER TABLE IF EXISTS assignment_help_request ALTER COLUMN amount_paid SET DEFAULT 0;
ALTER TABLE IF EXISTS assignment_help_request ALTER COLUMN payment_method SET DEFAULT 'ONLINE';
ALTER TABLE IF EXISTS assignment_help_request ALTER COLUMN payment_status SET DEFAULT 'PENDING';
ALTER TABLE IF EXISTS assignment_help_request ALTER COLUMN currency SET DEFAULT 'INR';
ALTER TABLE IF EXISTS assignment_help_request ALTER COLUMN status SET DEFAULT 'SUBMITTED';
ALTER TABLE IF EXISTS assignment_help_request ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX IF NOT EXISTS idx_assignment_help_created_at ON assignment_help_request (created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_assignment_help_razorpay_order_id ON assignment_help_request (razorpay_order_id) WHERE razorpay_order_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_assignment_help_user_id ON assignment_help_request (user_id);

CREATE TABLE IF NOT EXISTS prime_membership_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prime_membership_yearly_price DOUBLE PRECISION NOT NULL DEFAULT 299,
    assignment_standard_regular_price DOUBLE PRECISION NOT NULL DEFAULT 149,
    assignment_standard_prime_price DOUBLE PRECISION NOT NULL DEFAULT 99,
    assignment_express_regular_price DOUBLE PRECISION NOT NULL DEFAULT 249,
    assignment_express_prime_price DOUBLE PRECISION NOT NULL DEFAULT 149,
    assignment_urgent_regular_price DOUBLE PRECISION NOT NULL DEFAULT 399,
    assignment_urgent_prime_price DOUBLE PRECISION NOT NULL DEFAULT 249,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE IF EXISTS prime_membership_config ADD COLUMN IF NOT EXISTS prime_membership_yearly_price DOUBLE PRECISION;
ALTER TABLE IF EXISTS prime_membership_config ADD COLUMN IF NOT EXISTS assignment_standard_regular_price DOUBLE PRECISION;
ALTER TABLE IF EXISTS prime_membership_config ADD COLUMN IF NOT EXISTS assignment_standard_prime_price DOUBLE PRECISION;
ALTER TABLE IF EXISTS prime_membership_config ADD COLUMN IF NOT EXISTS assignment_express_regular_price DOUBLE PRECISION;
ALTER TABLE IF EXISTS prime_membership_config ADD COLUMN IF NOT EXISTS assignment_express_prime_price DOUBLE PRECISION;
ALTER TABLE IF EXISTS prime_membership_config ADD COLUMN IF NOT EXISTS assignment_urgent_regular_price DOUBLE PRECISION;
ALTER TABLE IF EXISTS prime_membership_config ADD COLUMN IF NOT EXISTS assignment_urgent_prime_price DOUBLE PRECISION;
ALTER TABLE IF EXISTS prime_membership_config ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS prime_membership_config ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

UPDATE prime_membership_config SET prime_membership_yearly_price = 299 WHERE prime_membership_yearly_price IS NULL;
UPDATE prime_membership_config SET assignment_standard_regular_price = 149 WHERE assignment_standard_regular_price IS NULL;
UPDATE prime_membership_config SET assignment_standard_prime_price = 99 WHERE assignment_standard_prime_price IS NULL;
UPDATE prime_membership_config SET assignment_express_regular_price = 249 WHERE assignment_express_regular_price IS NULL;
UPDATE prime_membership_config SET assignment_express_prime_price = 149 WHERE assignment_express_prime_price IS NULL;
UPDATE prime_membership_config SET assignment_urgent_regular_price = 399 WHERE assignment_urgent_regular_price IS NULL;
UPDATE prime_membership_config SET assignment_urgent_prime_price = 249 WHERE assignment_urgent_prime_price IS NULL;
UPDATE prime_membership_config SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE prime_membership_config SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL;

ALTER TABLE IF EXISTS prime_membership_config ALTER COLUMN prime_membership_yearly_price SET DEFAULT 299;
ALTER TABLE IF EXISTS prime_membership_config ALTER COLUMN assignment_standard_regular_price SET DEFAULT 149;
ALTER TABLE IF EXISTS prime_membership_config ALTER COLUMN assignment_standard_prime_price SET DEFAULT 99;
ALTER TABLE IF EXISTS prime_membership_config ALTER COLUMN assignment_express_regular_price SET DEFAULT 249;
ALTER TABLE IF EXISTS prime_membership_config ALTER COLUMN assignment_express_prime_price SET DEFAULT 149;
ALTER TABLE IF EXISTS prime_membership_config ALTER COLUMN assignment_urgent_regular_price SET DEFAULT 399;
ALTER TABLE IF EXISTS prime_membership_config ALTER COLUMN assignment_urgent_prime_price SET DEFAULT 249;
ALTER TABLE IF EXISTS prime_membership_config ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS prime_membership_config ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE IF EXISTS prime_membership_config ALTER COLUMN prime_membership_yearly_price SET NOT NULL;
ALTER TABLE IF EXISTS prime_membership_config ALTER COLUMN assignment_standard_regular_price SET NOT NULL;
ALTER TABLE IF EXISTS prime_membership_config ALTER COLUMN assignment_standard_prime_price SET NOT NULL;
ALTER TABLE IF EXISTS prime_membership_config ALTER COLUMN assignment_express_regular_price SET NOT NULL;
ALTER TABLE IF EXISTS prime_membership_config ALTER COLUMN assignment_express_prime_price SET NOT NULL;
ALTER TABLE IF EXISTS prime_membership_config ALTER COLUMN assignment_urgent_regular_price SET NOT NULL;
ALTER TABLE IF EXISTS prime_membership_config ALTER COLUMN assignment_urgent_prime_price SET NOT NULL;

CREATE TABLE IF NOT EXISTS ai_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assistant_type VARCHAR(64) NOT NULL,
    feedback_type VARCHAR(16) NOT NULL,
    prompt_text TEXT,
    response_text TEXT NOT NULL,
    reason_codes TEXT,
    feedback_details TEXT,
    chat_session_id VARCHAR(128) NOT NULL DEFAULT 'UNKNOWN',
    chat_session_started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    message_timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source_page VARCHAR(64) NOT NULL DEFAULT 'STUDY_CORNER',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE IF EXISTS ai_feedback ADD COLUMN IF NOT EXISTS assistant_type VARCHAR(64);
ALTER TABLE IF EXISTS ai_feedback ADD COLUMN IF NOT EXISTS feedback_type VARCHAR(16);
ALTER TABLE IF EXISTS ai_feedback ADD COLUMN IF NOT EXISTS prompt_text TEXT;
ALTER TABLE IF EXISTS ai_feedback ADD COLUMN IF NOT EXISTS response_text TEXT;
ALTER TABLE IF EXISTS ai_feedback ADD COLUMN IF NOT EXISTS reason_codes TEXT;
ALTER TABLE IF EXISTS ai_feedback ADD COLUMN IF NOT EXISTS feedback_details TEXT;
ALTER TABLE IF EXISTS ai_feedback ADD COLUMN IF NOT EXISTS chat_session_id VARCHAR(128);
ALTER TABLE IF EXISTS ai_feedback ADD COLUMN IF NOT EXISTS chat_session_started_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS ai_feedback ADD COLUMN IF NOT EXISTS message_timestamp TIMESTAMPTZ;
ALTER TABLE IF EXISTS ai_feedback ADD COLUMN IF NOT EXISTS source_page VARCHAR(64);
ALTER TABLE IF EXISTS ai_feedback ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;

UPDATE ai_feedback SET source_page = 'STUDY_CORNER' WHERE source_page IS NULL;
UPDATE ai_feedback SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE ai_feedback SET chat_session_id = 'UNKNOWN' WHERE chat_session_id IS NULL OR chat_session_id = '';
UPDATE ai_feedback SET chat_session_started_at = created_at WHERE chat_session_started_at IS NULL;
UPDATE ai_feedback SET message_timestamp = created_at WHERE message_timestamp IS NULL;

ALTER TABLE IF EXISTS ai_feedback ALTER COLUMN source_page SET DEFAULT 'STUDY_CORNER';
ALTER TABLE IF EXISTS ai_feedback ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS ai_feedback ALTER COLUMN chat_session_id SET DEFAULT 'UNKNOWN';
ALTER TABLE IF EXISTS ai_feedback ALTER COLUMN chat_session_started_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS ai_feedback ALTER COLUMN message_timestamp SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS ai_feedback ALTER COLUMN assistant_type SET NOT NULL;
ALTER TABLE IF EXISTS ai_feedback ALTER COLUMN feedback_type SET NOT NULL;
ALTER TABLE IF EXISTS ai_feedback ALTER COLUMN response_text SET NOT NULL;
ALTER TABLE IF EXISTS ai_feedback ALTER COLUMN chat_session_id SET NOT NULL;
ALTER TABLE IF EXISTS ai_feedback ALTER COLUMN chat_session_started_at SET NOT NULL;
ALTER TABLE IF EXISTS ai_feedback ALTER COLUMN message_timestamp SET NOT NULL;
ALTER TABLE IF EXISTS ai_feedback ALTER COLUMN source_page SET NOT NULL;
ALTER TABLE IF EXISTS ai_feedback ALTER COLUMN created_at SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ai_feedback_created_at ON ai_feedback (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_feedback_assistant_type ON ai_feedback (assistant_type);
CREATE INDEX IF NOT EXISTS idx_ai_feedback_feedback_type ON ai_feedback (feedback_type);
CREATE INDEX IF NOT EXISTS idx_ai_feedback_session_id ON ai_feedback (chat_session_id);
CREATE INDEX IF NOT EXISTS idx_ai_feedback_message_timestamp ON ai_feedback (message_timestamp DESC);

INSERT INTO prime_membership_config (
    prime_membership_yearly_price,
    assignment_standard_regular_price,
    assignment_standard_prime_price,
    assignment_express_regular_price,
    assignment_express_prime_price,
    assignment_urgent_regular_price,
    assignment_urgent_prime_price
)
SELECT 299, 149, 99, 249, 149, 399, 249
WHERE NOT EXISTS (SELECT 1 FROM prime_membership_config);

-- Seed base products for first run so Marketplace is never empty.
INSERT INTO product (name, description, price, image_url, category, branch, semester, is_prime_exclusive, rating)
SELECT 'Engineering Mechanics Notes Bundle', 'Complete unit-wise notes and solved examples for first-year mechanics.', 149,
       'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=900&q=80',
       'Notes', 'Mechanical Engineering', '2', FALSE, 4.6
WHERE NOT EXISTS (SELECT 1 FROM product);

INSERT INTO product (name, description, price, image_url, category, branch, semester, is_prime_exclusive, rating)
SELECT 'DSA Workbook + Previous Papers', 'Interview-focused workbook with solved PYQs and coding templates.', 299,
       'https://images.unsplash.com/photo-1513258496099-48168024aec0?auto=format&fit=crop&w=900&q=80',
       'Textbooks', 'Computer Engineering', '3', FALSE, 4.8
WHERE NOT EXISTS (SELECT 1 FROM product WHERE name = 'DSA Workbook + Previous Papers');

INSERT INTO product (name, description, price, image_url, category, branch, semester, is_prime_exclusive, rating)
SELECT 'Basic Electronics Lab Kit', 'Breadboard, sensors, jumper wires, and multimeter-ready accessories.', 999,
       'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80',
       'Lab Equipment', 'Electronics and Telecommunication Engineering', '4', FALSE, 4.5
WHERE NOT EXISTS (SELECT 1 FROM product WHERE name = 'Basic Electronics Lab Kit');

INSERT INTO product (name, description, price, image_url, category, branch, semester, is_prime_exclusive, rating)
SELECT 'Prime Exclusive: AI Model Training Toolkit', 'Dataset pack, model templates, and deployment starter resources.', 2199,
       'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=900&q=80',
       'Programming Tools', 'Artificial Intelligence and Data Science', '7', TRUE, 4.9
WHERE NOT EXISTS (SELECT 1 FROM product WHERE name = 'Prime Exclusive: AI Model Training Toolkit');

INSERT INTO skill_service (title, type, description, price, branch, semester)
SELECT 'Digital Electronics Assignment Review', 'Assignment',
       'Detailed review with corrections and explanation notes for submission.', 99,
       'Electronics and Telecommunication Engineering', '4'
WHERE NOT EXISTS (SELECT 1 FROM skill_service);

INSERT INTO skill_service (title, type, description, price, branch, semester)
SELECT 'Data Structures Practical Guidance', 'Practical',
       'Step-by-step coding support with viva preparation pointers.', 149,
       'Computer Engineering', '3'
WHERE NOT EXISTS (SELECT 1 FROM skill_service WHERE title = 'Data Structures Practical Guidance');

INSERT INTO skill_service (title, type, description, price, branch, semester)
SELECT 'Engineering Maths Tutoring Session', 'Tutoring',
       'One-on-one session focused on difficult modules and problem solving.', 199,
       'All Branches', '2'
WHERE NOT EXISTS (SELECT 1 FROM skill_service WHERE title = 'Engineering Maths Tutoring Session');

INSERT INTO skill_service (title, type, description, price, branch, semester)
SELECT 'Mini Project Architecture Consultation', 'Project',
       'Project planning support including tech stack and milestone roadmap.', 299,
       'Information Technology', '6'
WHERE NOT EXISTS (SELECT 1 FROM skill_service WHERE title = 'Mini Project Architecture Consultation');

INSERT INTO skill_service (title, type, description, price, branch, semester)
SELECT 'Mechanics Lab Journal Completion Help', 'Practical',
       'Format correction and experiment write-up guidance for timely submission.', 129,
       'Mechanical Engineering', '3'
WHERE NOT EXISTS (SELECT 1 FROM skill_service WHERE title = 'Mechanics Lab Journal Completion Help');

INSERT INTO skill_service (title, type, description, price, branch, semester)
SELECT 'AI/ML Assignment Debug Session', 'Assignment',
       'Hands-on debugging and model result interpretation support.', 249,
       'Artificial Intelligence and Data Science', '7'
WHERE NOT EXISTS (SELECT 1 FROM skill_service WHERE title = 'AI/ML Assignment Debug Session');
