-- MyCollegeMart PostgreSQL schema
-- This classpath copy ensures schema initialization works in Docker/Render.
-- Keep this file in sync with /database/schema.sql.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255),
    display_name VARCHAR(255),
    is_prime_member BOOLEAN NOT NULL DEFAULT FALSE,
    prime_expiry_date VARCHAR(255),
    google_id VARCHAR(255)
);

-- Patch existing installations where users table was created before these columns existed.
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS password VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS display_name VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS google_id VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS prime_expiry_date VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS is_prime_member BOOLEAN;
UPDATE users SET is_prime_member = FALSE WHERE is_prime_member IS NULL;
ALTER TABLE IF EXISTS users ALTER COLUMN is_prime_member SET DEFAULT FALSE;
ALTER TABLE IF EXISTS users ALTER COLUMN is_prime_member SET NOT NULL;

CREATE TABLE IF NOT EXISTS product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description TEXT,
    price DOUBLE PRECISION,
    image_url VARCHAR(255),
    category VARCHAR(255),
    branch VARCHAR(255),
    semester VARCHAR(32),
    is_prime_exclusive BOOLEAN NOT NULL DEFAULT FALSE,
    rating DOUBLE PRECISION,
    highlights_json TEXT,
    specs_json TEXT,
    external_video_url VARCHAR(1024),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS description VARCHAR(255);
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS price DOUBLE PRECISION;
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS image_url VARCHAR(255);
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS category VARCHAR(255);
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS branch VARCHAR(255);
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS semester VARCHAR(32);
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS is_prime_exclusive BOOLEAN;
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS rating DOUBLE PRECISION;
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS highlights_json TEXT;
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS specs_json TEXT;
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS external_video_url VARCHAR(1024);
ALTER TABLE IF EXISTS product ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS product ALTER COLUMN description TYPE TEXT;
UPDATE product SET is_prime_exclusive = FALSE WHERE is_prime_exclusive IS NULL;
ALTER TABLE IF EXISTS product ALTER COLUMN is_prime_exclusive SET DEFAULT FALSE;
ALTER TABLE IF EXISTS product ALTER COLUMN is_prime_exclusive SET NOT NULL;
UPDATE product SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
ALTER TABLE IF EXISTS product ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS user_wishlist (
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, product_id),
    CONSTRAINT fk_user_wishlist_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_wishlist_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT
);

ALTER TABLE IF EXISTS cart ADD COLUMN IF NOT EXISTS user_id BIGINT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_cart_user_id_unique ON cart (user_id);

CREATE TABLE IF NOT EXISTS cart_products (
    cart_id BIGINT NOT NULL,
    products_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT fk_cart_products_cart FOREIGN KEY (cart_id) REFERENCES cart (id),
    CONSTRAINT fk_cart_products_product FOREIGN KEY (products_id) REFERENCES product (id)
);

ALTER TABLE IF EXISTS cart_products ADD COLUMN IF NOT EXISTS quantity INTEGER;
UPDATE cart_products SET quantity = 1 WHERE quantity IS NULL;
ALTER TABLE IF EXISTS cart_products ALTER COLUMN quantity SET DEFAULT 1;
ALTER TABLE IF EXISTS cart_products ALTER COLUMN quantity SET NOT NULL;
ALTER TABLE IF EXISTS cart_products DROP CONSTRAINT IF EXISTS uk_cart_products_products;
CREATE UNIQUE INDEX IF NOT EXISTS idx_cart_products_cart_product_unique ON cart_products (cart_id, products_id);

CREATE INDEX IF NOT EXISTS idx_cart_user_id ON cart (user_id);

CREATE TABLE IF NOT EXISTS purchase_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    payment_method VARCHAR(64) NOT NULL,
    payment_status VARCHAR(64) NOT NULL,
    order_status VARCHAR(64) NOT NULL,
    delivery_option VARCHAR(255),
    subtotal DOUBLE PRECISION NOT NULL DEFAULT 0,
    wallet_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    amount_due DOUBLE PRECISION NOT NULL DEFAULT 0,
    amount_paid DOUBLE PRECISION NOT NULL DEFAULT 0,
    currency VARCHAR(8) NOT NULL DEFAULT 'INR',
    razorpay_order_id VARCHAR(255),
    razorpay_payment_id VARCHAR(255),
    razorpay_signature VARCHAR(255),
    items_json TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS order_number VARCHAR(255);
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS payment_method VARCHAR(64);
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS payment_status VARCHAR(64);
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS order_status VARCHAR(64);
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS delivery_option VARCHAR(255);
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS subtotal DOUBLE PRECISION;
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS wallet_amount DOUBLE PRECISION;
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS amount_due DOUBLE PRECISION;
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS amount_paid DOUBLE PRECISION;
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS currency VARCHAR(8);
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS razorpay_order_id VARCHAR(255);
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS razorpay_payment_id VARCHAR(255);
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS razorpay_signature VARCHAR(255);
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS items_json TEXT;
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS purchase_order ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

UPDATE purchase_order SET subtotal = 0 WHERE subtotal IS NULL;
UPDATE purchase_order SET wallet_amount = 0 WHERE wallet_amount IS NULL;
UPDATE purchase_order SET amount_due = 0 WHERE amount_due IS NULL;
UPDATE purchase_order SET amount_paid = 0 WHERE amount_paid IS NULL;
UPDATE purchase_order SET currency = 'INR' WHERE currency IS NULL;
UPDATE purchase_order SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE purchase_order SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL;

ALTER TABLE IF EXISTS purchase_order ALTER COLUMN subtotal SET DEFAULT 0;
ALTER TABLE IF EXISTS purchase_order ALTER COLUMN wallet_amount SET DEFAULT 0;
ALTER TABLE IF EXISTS purchase_order ALTER COLUMN amount_due SET DEFAULT 0;
ALTER TABLE IF EXISTS purchase_order ALTER COLUMN amount_paid SET DEFAULT 0;
ALTER TABLE IF EXISTS purchase_order ALTER COLUMN currency SET DEFAULT 'INR';
ALTER TABLE IF EXISTS purchase_order ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS purchase_order ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX IF NOT EXISTS idx_purchase_order_order_number ON purchase_order (order_number);
CREATE UNIQUE INDEX IF NOT EXISTS idx_purchase_order_razorpay_order_id ON purchase_order (razorpay_order_id) WHERE razorpay_order_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_purchase_order_user_id ON purchase_order (user_id);

CREATE TABLE IF NOT EXISTS media_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_type VARCHAR(64) NOT NULL,
    owner_id BIGINT NOT NULL,
    media_type VARCHAR(32) NOT NULL,
    file_name VARCHAR(255),
    content_type VARCHAR(255),
    file_size BIGINT,
    display_order INTEGER NOT NULL DEFAULT 0,
    data BYTEA NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE IF EXISTS media_asset ADD COLUMN IF NOT EXISTS owner_type VARCHAR(64);
ALTER TABLE IF EXISTS media_asset ADD COLUMN IF NOT EXISTS owner_id BIGINT;
ALTER TABLE IF EXISTS media_asset ADD COLUMN IF NOT EXISTS media_type VARCHAR(32);
ALTER TABLE IF EXISTS media_asset ADD COLUMN IF NOT EXISTS file_name VARCHAR(255);
ALTER TABLE IF EXISTS media_asset ADD COLUMN IF NOT EXISTS content_type VARCHAR(255);
ALTER TABLE IF EXISTS media_asset ADD COLUMN IF NOT EXISTS file_size BIGINT;
ALTER TABLE IF EXISTS media_asset ADD COLUMN IF NOT EXISTS display_order INTEGER;
ALTER TABLE IF EXISTS media_asset ADD COLUMN IF NOT EXISTS data BYTEA;
ALTER TABLE IF EXISTS media_asset ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;

UPDATE media_asset SET display_order = 0 WHERE display_order IS NULL;
ALTER TABLE IF EXISTS media_asset ALTER COLUMN display_order SET DEFAULT 0;
ALTER TABLE IF EXISTS media_asset ALTER COLUMN display_order SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_media_asset_owner ON media_asset (owner_type, owner_id, display_order);

CREATE TABLE IF NOT EXISTS skill_service (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    type VARCHAR(64) NOT NULL,
    description TEXT,
    price DOUBLE PRECISION NOT NULL DEFAULT 0,
    branch VARCHAR(255) NOT NULL,
    semester VARCHAR(16) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE IF EXISTS skill_service ADD COLUMN IF NOT EXISTS title VARCHAR(255);
ALTER TABLE IF EXISTS skill_service ADD COLUMN IF NOT EXISTS type VARCHAR(64);
ALTER TABLE IF EXISTS skill_service ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE IF EXISTS skill_service ADD COLUMN IF NOT EXISTS price DOUBLE PRECISION;
ALTER TABLE IF EXISTS skill_service ADD COLUMN IF NOT EXISTS branch VARCHAR(255);
ALTER TABLE IF EXISTS skill_service ADD COLUMN IF NOT EXISTS semester VARCHAR(16);
ALTER TABLE IF EXISTS skill_service ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
UPDATE skill_service SET price = 0 WHERE price IS NULL;
UPDATE skill_service SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
ALTER TABLE IF EXISTS skill_service ALTER COLUMN price SET DEFAULT 0;
ALTER TABLE IF EXISTS skill_service ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS assignment_help_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_service_id BIGINT,
    service_type VARCHAR(64) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    description TEXT,
    branch VARCHAR(255) NOT NULL,
    semester VARCHAR(16) NOT NULL,
    deadline VARCHAR(32) NOT NULL,
    total_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'SUBMITTED',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_assignment_help_skill_service FOREIGN KEY (skill_service_id) REFERENCES skill_service (id) ON DELETE SET NULL
);

ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS skill_service_id BIGINT;
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS service_type VARCHAR(64);
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS subject VARCHAR(255);
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS topic VARCHAR(255);
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS branch VARCHAR(255);
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS semester VARCHAR(16);
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS deadline VARCHAR(32);
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS total_amount DOUBLE PRECISION;
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS status VARCHAR(32);
ALTER TABLE IF EXISTS assignment_help_request ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
UPDATE assignment_help_request SET total_amount = 0 WHERE total_amount IS NULL;
UPDATE assignment_help_request SET status = 'SUBMITTED' WHERE status IS NULL;
UPDATE assignment_help_request SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
ALTER TABLE IF EXISTS assignment_help_request ALTER COLUMN total_amount SET DEFAULT 0;
ALTER TABLE IF EXISTS assignment_help_request ALTER COLUMN status SET DEFAULT 'SUBMITTED';
ALTER TABLE IF EXISTS assignment_help_request ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX IF NOT EXISTS idx_assignment_help_created_at ON assignment_help_request (created_at DESC);

-- Seed base products for first run so Marketplace is never empty.
INSERT INTO product (name, description, price, image_url, category, branch, semester, is_prime_exclusive, rating)
SELECT 'Engineering Mechanics Notes Bundle', 'Complete unit-wise notes and solved examples for first-year mechanics.', 149,
       'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=900&q=80',
       'Notes', 'Mechanical Engineering', '2', FALSE, 4.6
WHERE NOT EXISTS (SELECT 1 FROM product);

INSERT INTO product (name, description, price, image_url, category, branch, semester, is_prime_exclusive, rating)
SELECT 'DSA Workbook + Previous Papers', 'Interview-focused workbook with solved PYQs and coding templates.', 299,
       'https://images.unsplash.com/photo-1513258496099-48168024aec0?auto=format&fit=crop&w=900&q=80',
       'Textbooks', 'Computer Engineering', '3', FALSE, 4.8
WHERE NOT EXISTS (SELECT 1 FROM product WHERE name = 'DSA Workbook + Previous Papers');

INSERT INTO product (name, description, price, image_url, category, branch, semester, is_prime_exclusive, rating)
SELECT 'Basic Electronics Lab Kit', 'Breadboard, sensors, jumper wires, and multimeter-ready accessories.', 999,
       'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80',
       'Lab Equipment', 'Electronics and Telecommunication Engineering', '4', FALSE, 4.5
WHERE NOT EXISTS (SELECT 1 FROM product WHERE name = 'Basic Electronics Lab Kit');

INSERT INTO product (name, description, price, image_url, category, branch, semester, is_prime_exclusive, rating)
SELECT 'Prime Exclusive: AI Model Training Toolkit', 'Dataset pack, model templates, and deployment starter resources.', 2199,
       'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=900&q=80',
       'Programming Tools', 'Artificial Intelligence and Data Science', '7', TRUE, 4.9
WHERE NOT EXISTS (SELECT 1 FROM product WHERE name = 'Prime Exclusive: AI Model Training Toolkit');

INSERT INTO skill_service (title, type, description, price, branch, semester)
SELECT 'Digital Electronics Assignment Review', 'Assignment',
       'Detailed review with corrections and explanation notes for submission.', 99,
       'Electronics and Telecommunication Engineering', '4'
WHERE NOT EXISTS (SELECT 1 FROM skill_service);

INSERT INTO skill_service (title, type, description, price, branch, semester)
SELECT 'Data Structures Practical Guidance', 'Practical',
       'Step-by-step coding support with viva preparation pointers.', 149,
       'Computer Engineering', '3'
WHERE NOT EXISTS (SELECT 1 FROM skill_service WHERE title = 'Data Structures Practical Guidance');

INSERT INTO skill_service (title, type, description, price, branch, semester)
SELECT 'Engineering Maths Tutoring Session', 'Tutoring',
       'One-on-one session focused on difficult modules and problem solving.', 199,
       'All Branches', '2'
WHERE NOT EXISTS (SELECT 1 FROM skill_service WHERE title = 'Engineering Maths Tutoring Session');

INSERT INTO skill_service (title, type, description, price, branch, semester)
SELECT 'Mini Project Architecture Consultation', 'Project',
       'Project planning support including tech stack and milestone roadmap.', 299,
       'Information Technology', '6'
WHERE NOT EXISTS (SELECT 1 FROM skill_service WHERE title = 'Mini Project Architecture Consultation');

INSERT INTO skill_service (title, type, description, price, branch, semester)
SELECT 'Mechanics Lab Journal Completion Help', 'Practical',
       'Format correction and experiment write-up guidance for timely submission.', 129,
       'Mechanical Engineering', '3'
WHERE NOT EXISTS (SELECT 1 FROM skill_service WHERE title = 'Mechanics Lab Journal Completion Help');

INSERT INTO skill_service (title, type, description, price, branch, semester)
SELECT 'AI/ML Assignment Debug Session', 'Assignment',
       'Hands-on debugging and model result interpretation support.', 249,
       'Artificial Intelligence and Data Science', '7'
WHERE NOT EXISTS (SELECT 1 FROM skill_service WHERE title = 'AI/ML Assignment Debug Session');
